Repository opencodeiiita/Opencode-Collaborative-20, pull requests merged in 2020-01, with the labels that each got.

#206 #5 displayed participant list and their details
  css/style.css
  data/GitHubPro.md
  data/participants.json
  index.html
  js/main.js
Labels: Urgent, bug, work in progress

#258 added myself
  data/GitHubPro.md
Labels: conflicts

#270 Add myself as participant
  data/participants.json
Labels: conflicts, work in progress

#211 Name Added
  data/participants.json
Labels: conflicts
